import {
    DocumentTextIcon,
    ClockIcon,
    TrashIcon,
    UserIcon,
    QuestionMarkCircleIcon,
    PowerIcon,
    PlusCircleIcon,
    ChevronDownIcon,
    ArrowUpTrayIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    EllipsisVerticalIcon,
    ArrowUturnLeftIcon,
    ArrowUturnRightIcon,
    PrinterIcon,
    ArrowDownOnSquareStackIcon,
    DocumentDuplicateIcon,
    ArrowDownOnSquareIcon,
    ShieldCheckIcon,
    PhoneIcon,
    EnvelopeIcon

} from "@heroicons/react/24/outline";

export {
    DocumentTextIcon,
    ClockIcon,
    TrashIcon,
    UserIcon,
    QuestionMarkCircleIcon,
    PowerIcon,
    PlusCircleIcon,
    ChevronDownIcon,
    ArrowUpTrayIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    EllipsisVerticalIcon,
    ArrowUturnLeftIcon,
    ArrowUturnRightIcon,
    PrinterIcon,
    ArrowDownOnSquareStackIcon,
    DocumentDuplicateIcon,
    ArrowDownOnSquareIcon,
    ShieldCheckIcon,
    PhoneIcon,
    EnvelopeIcon
};
